### ISSUE TITLE
Unrecognized resource type: litecoin_address

### ISSUE THREAD

**Issue by shked0wn** [coinbase/coinbase-php#137]
Hello,
Mapper fails when calling $client->getAccountTransactions($account), with the following error : 
 
Unrecognized resource type: litecoin_address

Stacktrace : 
Mapper->createResource('litecoin_address', array('resource' => 'litecoin_address', 'address' => 'xxxxxxxxx', 'currency' => 'LTC'))

Do you have a workaround ?

**Comment by victor-suriel** [comment]
Hi there,

I had the same problems with Ethereum Addresses. The problem is that Ether and Litecoin are currently not fully implemented in the coinbase php API.

After I directly went into the source code to add all of the functionalities for Ether, I was able to use the API for Ether with no problems.

I was actually visiting this Github precisely to bring this up. Maybe there is some way I can create a pull request for the coinbase devs to look over my ETH additions and add them?

**Comment by shked0wn** [comment]
Hello, I have done the same thing for ltc address, so for now i'm using my fork. And I opened a pull request. Yes I think you should do a pull request !

**Comment by sds** [comment]
Addressed by #138.
