### ISSUE TITLE
I sent an order and the balance doesn't match?!

### ISSUE THREAD

**Issue by AlexisWilke** [coinbase/coinbase-php#160]
I sent the following order against a balance of USD $100.00

    {
      "client_oid":"17215070-e815-40b0-a6ea-680f48e61303",
      "time_in_force":"GTC",
      "type":"limit",
      "price":"70.00",
      "post_only":true,
      "side":"buy",
      "product_id":"BTC-USD",
      "stp":"dc",
      "size":"0.01000000"
    }

The order shows up as expected when I go see the website interface, however, my balance was updated and now looks like: $99.30 when I expected $30.

![image](https://user-images.githubusercontent.com/1028617/38168147-6cac089e-34f9-11e8-97a2-869a485ebd5b.png)

The returned JSON seems to look just fine:

    {
      "fill_fees": "0.0000000000000000",
      "id": "08d3b9bd-2f2f-4406-8f9a-dd7917272278",
      "size": "0.01000000",
      "status": "pending",
      "filled_size": "0.00000000",
      "post_only": true,
      "side": "buy",
      "executed_value": "0.0000000000000000",
      "price": "70.00000000",
      "product_id": "BTC-USD",
      "stp": "dc",
      "created_at": "2018-03-31T22:12:59.337479Z",
      "type": "limit",
      "settled": false,
      "time_in_force": "GTC"
    }

It could be that this has something to do with this issue:
https://github.com/coinbase/gdax-tt/issues/199

**Comment by sds** [comment]
Hey @AlexisWilke, as this issue doesn't relate to the PHP library itself and is about API behavior, the best way to find an answer or report a bug is by opening a [support ticket](https://support.gdax.com/) so that someone can provide you with an authoritative answer.

The API this library integrates with is for Coinbase, which is a separate product, hence why we strongly recommend you find your answer from GDAX support. Thanks!
