### ISSUE TITLE
Can't get transactions from address ETH

### ISSUE THREAD

**Issue by levis012** [coinbase/coinbase-php#181]
I have make a call to get transactions from ETH.
This is my code
`
$apiKey = env('COINBASE_API_KEY');
            $apiSecret = env('COINBASE_SECRET');
$acountEthId = 'XXXXX';
            $configuration = Configuration::apiKey($apiKey, $apiSecret);
            $client = Client::create($configuration);
            $account = $client->getAccount($acountEthId);
            $address = $client->getAccountAddress($account, $address);
            $listTransaction = $client->getAddressTransactions($address)->all();
`

And  got the response:

`
Client error: GET https://api.coinbase.com/v2/accounts/:accountId/addresses/:ETHaddress resulted in a 404 Not Found response:\n
      {"errors":[{"id":"not_found","message":"Not found"}]}
`

Please help me some fix.

**Comment by sds** [comment]
Hey @levis012, this issue seems unrelated to the PHP package itself and requires actual details about the account and address you're trying to query. 

Best way forward is to [contact our support team](https://support.coinbase.com/) to help you, as we don't discuss private account details on GitHub. Hope that helps!
