### ISSUE TITLE
EthereumAddress class misspelt

### ISSUE THREAD

**Issue by cmdlucas** [coinbase/coinbase-php#186]
The "EthereumAddress" class was not spelt correctly and thus confusing most especially when referencing it. On the current version "~2.0" it is spelt as "EthrereumAddress".

Also, is it an oversight that BitcoinCashAddress is missing from the package whereas it's Network equivalent is present?

Although one could create the Address classes by extending Resource, it is much more convenient just having to reference it directly from the package.

**Comment by swiftsack** [comment]
Using the API, I get an error that says 

`LogicException in Mapper.php line 124: The Coinbase API only accepts transactions to an account, email, or bitcoin address"`

It is understandable why I get this error since I was trying to use an EthereumAddress. But is there any real reason for this limitation?? Why are other cryptocurrency addresses not allowed?

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
